-- 自動生成。手で編集しないこと。
-- 再生成: node scripts/gen-seed.js
--
-- 【本番に流してよい】delete文を含まない。ダミーカード20件をinsert or ignoreで
-- 入れるだけなので、複数回流しても本番データを壊さない。

insert or ignore into cards (id, artisan_id, name, name_kana, artisan_name, description, hp_url, region, address, history, tags, lang, created_at, updated_at) values ('c001', 'org-demo', '越前和紙', 'えちぜんわし', '越前和紙の里 パピルス館', '予約なしで紙漉き体験ができる施設。所要20〜40分で、漉いた紙はその場で持ち帰れる。隣接する卯立の工芸館では、原料づくりから天日干しまでの全工程を見学できる。', 'https://www.echizenwashi.jp/', '福井県', '福井県越前市新在家町8-44', '越前和紙は1500年の歴史を持つとされる産地。', '和紙,紙漉き,体験できる,文具', 'ja', 1788346810738, 1788346810738);
insert or ignore into cards (id, artisan_id, name, name_kana, artisan_name, description, hp_url, region, address, history, tags, lang, created_at, updated_at) values ('c002', 'org-demo', '輪島塗', 'わじまぬり', '輪島塗会館（輪島漆器商工業協同組合）', '1階に約60軒の漆器店が出店する共同ショップ、2階に製作工程と歴史の資料展示室がある。輪島塗は百以上の工程を分業でこなす。', 'https://wajimanuri.or.jp/', '石川県', '石川県輪島市河井町24-55', '輪島漆器商工業協同組合が運営。', '漆器,食器,見学できる,沈金', 'ja', 1788346810738, 1788346810738);
insert or ignore into cards (id, artisan_id, name, name_kana, artisan_name, description, hp_url, region, address, history, tags, lang, created_at, updated_at) values ('c003', 'org-demo', '西陣織', 'にしじんおり', '西陣織会館（西陣織工業組合）', '職人による手織の実演、蚕の飼育や座繰りの見学ができる。手織体験では20×30cm程度のテーブルセンターを織れる。西陣織は工程ごとに職人が分かれる分業制。', 'https://nishijin.or.jp/', '京都府', '京都府京都市上京区西堀川通元誓願寺上ル竪門前町414', '西陣織工業組合が運営。', '織物,絹,帯,体験できる,実演', 'ja', 1788346810738, 1788346810738);
insert or ignore into cards (id, artisan_id, name, name_kana, artisan_name, description, hp_url, region, address, history, tags, lang, created_at, updated_at) values ('c004', 'org-demo', '南部鉄器', 'なんぶてっき', '岩鋳鉄器館', '南部鉄器の製造工程を無料で見学できる工場併設の資料館。鋳型に文様を一粒ずつ押していくあられ模様の工程が見られる。使うほど内側に膜ができて湯の味が変わる。', 'https://iwachu.co.jp/', '岩手県', '岩手県盛岡市南仙北2-23-9', '南部鉄器は江戸期の藩の保護から発展した。', '金工,鉄,茶道具,見学できる,急須', 'ja', 1788346810738, 1788346810738);
insert or ignore into cards (id, artisan_id, name, name_kana, artisan_name, description, hp_url, region, address, history, tags, lang, created_at, updated_at) values ('d001', 'artisan-demo', '小鹿田焼 飛び鉋の小鉢', 'おんたやき とびかんなのこばち', '（架空）坂本 陽一', '鉋を当てて規則的な刻みを入れる飛び鉋の小鉢。土は地元の山から掘り、唐臼で搗いて作る。素朴で厚みがある。', null, '大分県', '大分県日田市源栄町皿山', '小鹿田焼は江戸中期から続く。一子相伝で作り手を増やさない方針を守っている。', '陶磁器,陶器,器,食器', 'ja', 1788346810738, 1788346810738);
insert or ignore into cards (id, artisan_id, name, name_kana, artisan_name, description, hp_url, region, address, history, tags, lang, created_at, updated_at) values ('d002', 'artisan-demo', '津軽塗 七々子塗の箸', 'つがるぬり ななこぬりのはし', '（架空）工藤 佳子', '菜の花の種を蒔いて模様を作る七々子塗。研ぎ出すと小さな輪が浮かぶ。四十以上の工程を経て仕上がる。', null, '青森県', '青森県弘前市', '藩政時代に始まった塗り。', '漆器,食器,箸', 'ja', 1788346810738, 1788346810738);
insert or ignore into cards (id, artisan_id, name, name_kana, artisan_name, description, hp_url, region, address, history, tags, lang, created_at, updated_at) values ('d003', 'artisan-demo', '琉球ガラス 泡入りのグラス', 'りゅうきゅうがらす あわいりのぐらす', '（架空）比嘉 直人', '廃瓶を溶かして再生した青いガラス。あえて気泡を残しており、光を通すと水中のように見える。厚手で手に重い。', null, '沖縄県', '沖縄県糸満市', '戦後の物資不足で米軍の廃瓶を使ったのが始まり。', 'ガラス,器,食器,夏', 'ja', 1788346810738, 1788346810738);
insert or ignore into cards (id, artisan_id, name, name_kana, artisan_name, description, hp_url, region, address, history, tags, lang, created_at, updated_at) values ('d004', 'artisan-demo', '三味線 紅木の棹', 'しゃみせん こうきのさお', '（架空）遠藤 常吉', 'インド産の紅木を十年以上寝かせてから削り出す棹。継ぎ目が指に触れないよう精度を合わせる。木の詰まり具合で音が変わる。', null, '東京都', '東京都台東区', '棹だけを専門に手がけ、組み立ては別の職人に渡す分業。', '楽器,木工,三味線,音が鳴る', 'ja', 1788346810738, 1788346810738);
insert or ignore into cards (id, artisan_id, name, name_kana, artisan_name, description, hp_url, region, address, history, tags, lang, created_at, updated_at) values ('d005', 'artisan-demo', '尺八 地無し管', 'しゃくはち じなしかん', '（架空）中村 玄樹', '内側に漆を塗り重ねない地無しの竹管。竹そのものの内径で鳴らすため個体差が大きく、息の入れ方で音色が変わる。', null, '京都府', '京都府京都市', '江戸期の虚無僧尺八の作り方を復元。', '楽器,竹,尺八,音が鳴る', 'ja', 1788346810738, 1788346810738);
insert or ignore into cards (id, artisan_id, name, name_kana, artisan_name, description, hp_url, region, address, history, tags, lang, created_at, updated_at) values ('d006', 'artisan-demo', '和太鼓 欅のくり抜き胴', 'わだいこ けやきのくりぬきどう', '（架空）浅野 武', '一本の欅を丸ごとくり抜いた胴。乾燥に数年かけ、割れが出ないのを確かめてから皮を張る。低く長く響く。', null, '石川県', '石川県白山市', '原木の確保が年々難しくなっている。', '楽器,木工,太鼓,音が鳴る', 'ja', 1788346810738, 1788346810738);
insert or ignore into cards (id, artisan_id, name, name_kana, artisan_name, description, hp_url, region, address, history, tags, lang, created_at, updated_at) values ('d007', 'artisan-demo', '駿河竹千筋細工 虫籠', 'するがたけせんすじざいく むしかご', '（架空）杉山 隆一', '丸く削った竹ひごを差し込んで組む籠。接着剤を使わず竹の弾力だけで留める。透けるほど細い。', null, '静岡県', '静岡県静岡市', '江戸後期に武士の内職から広まった。作り手は現在十数人。', '竹工,小物,竹,夏', 'ja', 1788346810738, 1788346810738);
insert or ignore into cards (id, artisan_id, name, name_kana, artisan_name, description, hp_url, region, address, history, tags, lang, created_at, updated_at) values ('d008', 'artisan-demo', '備前焼 緋襷の徳利', 'びぜんやき ひだすきのとっくり', '（架空）森本 一馬', '釉薬を使わず、藁を巻いて焼くと赤い線が走る。窯の中の置き場所で色が決まるため、同じものは二つとない。', null, '岡山県', '岡山県備前市伊部', '備前は釉薬を使わない焼き締めを千年続けている。', '陶磁器,陶器,酒器,器', 'ja', 1788346810738, 1788346810738);
insert or ignore into cards (id, artisan_id, name, name_kana, artisan_name, description, hp_url, region, address, history, tags, lang, created_at, updated_at) values ('d009', 'artisan-demo', '京友禅 手描きの風呂敷', 'きょうゆうぜん てがきのふろしき', '（架空）岡村 貴子', '糊で輪郭を置き、筆で一色ずつ挿していく手描き友禅。色の境が滲まない。淡い色を何度も重ねて深さを出す。', null, '京都府', '京都府京都市', '下絵・糊置き・彩色が別の職人に分かれる分業制。', '染物,布,友禅', 'ja', 1788346810738, 1788346810738);
insert or ignore into cards (id, artisan_id, name, name_kana, artisan_name, description, hp_url, region, address, history, tags, lang, created_at, updated_at) values ('d010', 'artisan-demo', '大館曲げわっぱ 弁当箱', 'おおだてまげわっぱ べんとうばこ', '（架空）佐藤 建二', '秋田杉を煮て柔らかくし、曲げて桜の皮で縫い留める。木が余分な水分を吸うので冷めた米がべたつかない。', null, '秋田県', '秋田県大館市', '藩政期に下級武士の内職として奨励された。', '木工,弁当箱,杉,贈り物', 'ja', 1788346810738, 1788346810738);
insert or ignore into cards (id, artisan_id, name, name_kana, artisan_name, description, hp_url, region, address, history, tags, lang, created_at, updated_at) values ('d011', 'artisan-demo', '江戸切子 魚子紋の冷酒杯', 'えどきりこ ななこもんのれいしゅはい', '（架空）堀口 誠', '色被せガラスの表面を回転砥石で削り、細かい格子を刻む。透明な部分と色の対比が出る。手に取ると角がざらつく。', null, '東京都', '東京都江東区', '幕末に江戸で始まったガラス加工。', 'ガラス,酒器,切子,夏,贈り物', 'ja', 1788346810738, 1788346810738);
insert or ignore into cards (id, artisan_id, name, name_kana, artisan_name, description, hp_url, region, address, history, tags, lang, created_at, updated_at) values ('d012', 'artisan-demo', '高岡銅器 花器', 'たかおかどうき かき', '（架空）般若 秀樹', '鋳込んだ銅に薬品をかけて色を出す着色仕上げ。緑青とも黒ともつかない色に変化する。ずっしり重い。', null, '富山県', '富山県高岡市', '加賀藩が鋳物師を招いたのが始まり。着色は専門の職人が担う。', '金工,銅,花器', 'ja', 1788346810738, 1788346810738);
insert or ignore into cards (id, artisan_id, name, name_kana, artisan_name, description, hp_url, region, address, history, tags, lang, created_at, updated_at) values ('d013', 'artisan-demo', '本場大島紬 泥染めの反物', 'ほんばおおしまつむぎ どろぞめのたんもの', '（架空）肥後 明美', 'テーチ木で染めた糸を泥田に浸して黒く発色させる。泥に含まれる鉄分と反応する。軽くて皺になりにくい。', null, '鹿児島県', '鹿児島県奄美市', '締機・泥染め・織りがそれぞれ別の職人に分かれる。', '織物,絹,紬', 'ja', 1788346810738, 1788346810738);
insert or ignore into cards (id, artisan_id, name, name_kana, artisan_name, description, hp_url, region, address, history, tags, lang, created_at, updated_at) values ('d014', 'artisan-demo', '播州そろばん 樺の玉', 'ばんしゅうそろばん かばのたま', '（架空）宮永 敏夫', '樺の玉を一粒ずつ削り、竹の軸に通す。指で弾いたときの音と止まり方が揃うよう玉の重さを合わせる。', null, '兵庫県', '兵庫県小野市', '玉・軸・枠が別々の職人による分業。', '木工,文具,そろばん,音が鳴る', 'ja', 1788346810738, 1788346810738);
insert or ignore into cards (id, artisan_id, name, name_kana, artisan_name, description, hp_url, region, address, history, tags, lang, created_at, updated_at) values ('d015', 'artisan-demo', '岩谷堂箪笥 鉄製手掛かり', 'いわやどうたんす てつせいてがかり', '（架空）及川 正', '欅の箪笥に打つ手打ちの鉄金具。唐草を透かし彫りにする。木地師と金具師が別々に作り、最後に合わせる。', null, '岩手県', '岩手県奥州市', '金具を打てる職人が減っている。', '木工,家具,金具', 'ja', 1788346810738, 1788346810738);
insert or ignore into cards (id, artisan_id, name, name_kana, artisan_name, description, hp_url, region, address, history, tags, lang, created_at, updated_at) values ('d016', 'artisan-demo', '丸亀うちわ 平柄', 'まるがめうちわ ひらえ', '（架空）香川 実', '一本の竹を割いて骨と柄を一体で作る平柄。骨が細かいほど風が柔らかい。和紙を貼って縁を留める。', null, '香川県', '香川県丸亀市', '金比羅参りの土産として江戸期に広まった。', '竹工,うちわ,夏,贈り物', 'ja', 1788346810738, 1788346810738);
