// ローカル開発用のシードデータ。
//
// 紹介機能が作る cards テーブルと同じ形にしてある。
// 統合後は紹介機能が登録したデータを読むので、このファイルは不要になる。
//
// artisan_name に「（架空）」が付いているものは検証用のダミー。
// 産地と品目は実在するが、工房名・職人名は架空。
// 付いていない4件は施設名・住所・公式サイトを実在確認済み（2026-08時点）。

export const cards = [
  {
    id: "c001",
    artisan_id: "org-demo",
    name: "越前和紙",
    name_kana: "えちぜんわし",
    artisan_name: "越前和紙の里 パピルス館",
    description:
      "予約なしで紙漉き体験ができる施設。所要20〜40分で、漉いた紙はその場で持ち帰れる。隣接する卯立の工芸館では、原料づくりから天日干しまでの全工程を見学できる。",
    hp_url: "https://www.echizenwashi.jp/",
    region: "福井県",
    address: "福井県越前市新在家町8-44",
    history: "越前和紙は1500年の歴史を持つとされる産地。",
    tags: "和紙,紙漉き,体験できる,文具",
    lang: "ja",
  },
  {
    id: "c002",
    artisan_id: "org-demo",
    name: "輪島塗",
    name_kana: "わじまぬり",
    artisan_name: "輪島塗会館（輪島漆器商工業協同組合）",
    description:
      "1階に約60軒の漆器店が出店する共同ショップ、2階に製作工程と歴史の資料展示室がある。輪島塗は百以上の工程を分業でこなす。",
    hp_url: "https://wajimanuri.or.jp/",
    region: "石川県",
    address: "石川県輪島市河井町24-55",
    history: "輪島漆器商工業協同組合が運営。",
    tags: "漆器,食器,見学できる,沈金",
    lang: "ja",
  },
  {
    id: "c003",
    artisan_id: "org-demo",
    name: "西陣織",
    name_kana: "にしじんおり",
    artisan_name: "西陣織会館（西陣織工業組合）",
    description:
      "職人による手織の実演、蚕の飼育や座繰りの見学ができる。手織体験では20×30cm程度のテーブルセンターを織れる。西陣織は工程ごとに職人が分かれる分業制。",
    hp_url: "https://nishijin.or.jp/",
    region: "京都府",
    address: "京都府京都市上京区西堀川通元誓願寺上ル竪門前町414",
    history: "西陣織工業組合が運営。",
    tags: "織物,絹,帯,体験できる,実演",
    lang: "ja",
  },
  {
    id: "c004",
    artisan_id: "org-demo",
    name: "南部鉄器",
    name_kana: "なんぶてっき",
    artisan_name: "岩鋳鉄器館",
    description:
      "南部鉄器の製造工程を無料で見学できる工場併設の資料館。鋳型に文様を一粒ずつ押していくあられ模様の工程が見られる。使うほど内側に膜ができて湯の味が変わる。",
    hp_url: "https://iwachu.co.jp/",
    region: "岩手県",
    address: "岩手県盛岡市南仙北2-23-9",
    history: "南部鉄器は江戸期の藩の保護から発展した。",
    tags: "金工,鉄,茶道具,見学できる,急須",
    lang: "ja",
  },
  {
    id: "d001",
    artisan_id: "artisan-demo",
    name: "小鹿田焼 飛び鉋の小鉢",
    name_kana: "おんたやき とびかんなのこばち",
    artisan_name: "（架空）坂本 陽一",
    description:
      "鉋を当てて規則的な刻みを入れる飛び鉋の小鉢。土は地元の山から掘り、唐臼で搗いて作る。素朴で厚みがある。",
    hp_url: null,
    region: "大分県",
    address: "大分県日田市源栄町皿山",
    history: "小鹿田焼は江戸中期から続く。一子相伝で作り手を増やさない方針を守っている。",
    tags: "陶磁器,陶器,器,食器",
    lang: "ja",
  },
  {
    id: "d002",
    artisan_id: "artisan-demo",
    name: "津軽塗 七々子塗の箸",
    name_kana: "つがるぬり ななこぬりのはし",
    artisan_name: "（架空）工藤 佳子",
    description:
      "菜の花の種を蒔いて模様を作る七々子塗。研ぎ出すと小さな輪が浮かぶ。四十以上の工程を経て仕上がる。",
    hp_url: null,
    region: "青森県",
    address: "青森県弘前市",
    history: "藩政時代に始まった塗り。",
    tags: "漆器,食器,箸",
    lang: "ja",
  },
  {
    id: "d003",
    artisan_id: "artisan-demo",
    name: "琉球ガラス 泡入りのグラス",
    name_kana: "りゅうきゅうがらす あわいりのぐらす",
    artisan_name: "（架空）比嘉 直人",
    description:
      "廃瓶を溶かして再生した青いガラス。あえて気泡を残しており、光を通すと水中のように見える。厚手で手に重い。",
    hp_url: null,
    region: "沖縄県",
    address: "沖縄県糸満市",
    history: "戦後の物資不足で米軍の廃瓶を使ったのが始まり。",
    tags: "ガラス,器,食器,夏",
    lang: "ja",
  },
  {
    id: "d004",
    artisan_id: "artisan-demo",
    name: "三味線 紅木の棹",
    name_kana: "しゃみせん こうきのさお",
    artisan_name: "（架空）遠藤 常吉",
    description:
      "インド産の紅木を十年以上寝かせてから削り出す棹。継ぎ目が指に触れないよう精度を合わせる。木の詰まり具合で音が変わる。",
    hp_url: null,
    region: "東京都",
    address: "東京都台東区",
    history: "棹だけを専門に手がけ、組み立ては別の職人に渡す分業。",
    tags: "楽器,木工,三味線,音が鳴る",
    lang: "ja",
  },
  {
    id: "d005",
    artisan_id: "artisan-demo",
    name: "尺八 地無し管",
    name_kana: "しゃくはち じなしかん",
    artisan_name: "（架空）中村 玄樹",
    description:
      "内側に漆を塗り重ねない地無しの竹管。竹そのものの内径で鳴らすため個体差が大きく、息の入れ方で音色が変わる。",
    hp_url: null,
    region: "京都府",
    address: "京都府京都市",
    history: "江戸期の虚無僧尺八の作り方を復元。",
    tags: "楽器,竹,尺八,音が鳴る",
    lang: "ja",
  },
  {
    id: "d006",
    artisan_id: "artisan-demo",
    name: "和太鼓 欅のくり抜き胴",
    name_kana: "わだいこ けやきのくりぬきどう",
    artisan_name: "（架空）浅野 武",
    description:
      "一本の欅を丸ごとくり抜いた胴。乾燥に数年かけ、割れが出ないのを確かめてから皮を張る。低く長く響く。",
    hp_url: null,
    region: "石川県",
    address: "石川県白山市",
    history: "原木の確保が年々難しくなっている。",
    tags: "楽器,木工,太鼓,音が鳴る",
    lang: "ja",
  },
  {
    id: "d007",
    artisan_id: "artisan-demo",
    name: "駿河竹千筋細工 虫籠",
    name_kana: "するがたけせんすじざいく むしかご",
    artisan_name: "（架空）杉山 隆一",
    description:
      "丸く削った竹ひごを差し込んで組む籠。接着剤を使わず竹の弾力だけで留める。透けるほど細い。",
    hp_url: null,
    region: "静岡県",
    address: "静岡県静岡市",
    history: "江戸後期に武士の内職から広まった。作り手は現在十数人。",
    tags: "竹工,小物,竹,夏",
    lang: "ja",
  },
  {
    id: "d008",
    artisan_id: "artisan-demo",
    name: "備前焼 緋襷の徳利",
    name_kana: "びぜんやき ひだすきのとっくり",
    artisan_name: "（架空）森本 一馬",
    description:
      "釉薬を使わず、藁を巻いて焼くと赤い線が走る。窯の中の置き場所で色が決まるため、同じものは二つとない。",
    hp_url: null,
    region: "岡山県",
    address: "岡山県備前市伊部",
    history: "備前は釉薬を使わない焼き締めを千年続けている。",
    tags: "陶磁器,陶器,酒器,器",
    lang: "ja",
  },
  {
    id: "d009",
    artisan_id: "artisan-demo",
    name: "京友禅 手描きの風呂敷",
    name_kana: "きょうゆうぜん てがきのふろしき",
    artisan_name: "（架空）岡村 貴子",
    description:
      "糊で輪郭を置き、筆で一色ずつ挿していく手描き友禅。色の境が滲まない。淡い色を何度も重ねて深さを出す。",
    hp_url: null,
    region: "京都府",
    address: "京都府京都市",
    history: "下絵・糊置き・彩色が別の職人に分かれる分業制。",
    tags: "染物,布,友禅",
    lang: "ja",
  },
  {
    id: "d010",
    artisan_id: "artisan-demo",
    name: "大館曲げわっぱ 弁当箱",
    name_kana: "おおだてまげわっぱ べんとうばこ",
    artisan_name: "（架空）佐藤 建二",
    description:
      "秋田杉を煮て柔らかくし、曲げて桜の皮で縫い留める。木が余分な水分を吸うので冷めた米がべたつかない。",
    hp_url: null,
    region: "秋田県",
    address: "秋田県大館市",
    history: "藩政期に下級武士の内職として奨励された。",
    tags: "木工,弁当箱,杉,贈り物",
    lang: "ja",
  },
  {
    id: "d011",
    artisan_id: "artisan-demo",
    name: "江戸切子 魚子紋の冷酒杯",
    name_kana: "えどきりこ ななこもんのれいしゅはい",
    artisan_name: "（架空）堀口 誠",
    description:
      "色被せガラスの表面を回転砥石で削り、細かい格子を刻む。透明な部分と色の対比が出る。手に取ると角がざらつく。",
    hp_url: null,
    region: "東京都",
    address: "東京都江東区",
    history: "幕末に江戸で始まったガラス加工。",
    tags: "ガラス,酒器,切子,夏,贈り物",
    lang: "ja",
  },
  {
    id: "d012",
    artisan_id: "artisan-demo",
    name: "高岡銅器 花器",
    name_kana: "たかおかどうき かき",
    artisan_name: "（架空）般若 秀樹",
    description:
      "鋳込んだ銅に薬品をかけて色を出す着色仕上げ。緑青とも黒ともつかない色に変化する。ずっしり重い。",
    hp_url: null,
    region: "富山県",
    address: "富山県高岡市",
    history: "加賀藩が鋳物師を招いたのが始まり。着色は専門の職人が担う。",
    tags: "金工,銅,花器",
    lang: "ja",
  },
  {
    id: "d013",
    artisan_id: "artisan-demo",
    name: "本場大島紬 泥染めの反物",
    name_kana: "ほんばおおしまつむぎ どろぞめのたんもの",
    artisan_name: "（架空）肥後 明美",
    description:
      "テーチ木で染めた糸を泥田に浸して黒く発色させる。泥に含まれる鉄分と反応する。軽くて皺になりにくい。",
    hp_url: null,
    region: "鹿児島県",
    address: "鹿児島県奄美市",
    history: "締機・泥染め・織りがそれぞれ別の職人に分かれる。",
    tags: "織物,絹,紬",
    lang: "ja",
  },
  {
    id: "d014",
    artisan_id: "artisan-demo",
    name: "播州そろばん 樺の玉",
    name_kana: "ばんしゅうそろばん かばのたま",
    artisan_name: "（架空）宮永 敏夫",
    description:
      "樺の玉を一粒ずつ削り、竹の軸に通す。指で弾いたときの音と止まり方が揃うよう玉の重さを合わせる。",
    hp_url: null,
    region: "兵庫県",
    address: "兵庫県小野市",
    history: "玉・軸・枠が別々の職人による分業。",
    tags: "木工,文具,そろばん,音が鳴る",
    lang: "ja",
  },
  {
    id: "d015",
    artisan_id: "artisan-demo",
    name: "岩谷堂箪笥 鉄製手掛かり",
    name_kana: "いわやどうたんす てつせいてがかり",
    artisan_name: "（架空）及川 正",
    description:
      "欅の箪笥に打つ手打ちの鉄金具。唐草を透かし彫りにする。木地師と金具師が別々に作り、最後に合わせる。",
    hp_url: null,
    region: "岩手県",
    address: "岩手県奥州市",
    history: "金具を打てる職人が減っている。",
    tags: "木工,家具,金具",
    lang: "ja",
  },
  {
    id: "d016",
    artisan_id: "artisan-demo",
    name: "丸亀うちわ 平柄",
    name_kana: "まるがめうちわ ひらえ",
    artisan_name: "（架空）香川 実",
    description:
      "一本の竹を割いて骨と柄を一体で作る平柄。骨が細かいほど風が柔らかい。和紙を貼って縁を留める。",
    hp_url: null,
    region: "香川県",
    address: "香川県丸亀市",
    history: "金比羅参りの土産として江戸期に広まった。",
    tags: "竹工,うちわ,夏,贈り物",
    lang: "ja",
  },

  // ---- ここから追加分（2026-09-04）。デモで各ジャンル最低5件になるよう補充。
  // 既存データと同じ形式・調子で、地域は東北・中国・四国・九州を厚めにした。
  // artisan_name は必ず「（架空）」で始める（is_dummy判定 / features/search/db.js）。
  // 産地・品目は実在するが、工房名・職人名・住所番地は架空。

  // --- 染物 +4 ---
  {
    id: "d017",
    artisan_id: "artisan-demo",
    name: "紅型",
    name_kana: "びんがた",
    artisan_name: "（架空）比嘉 光男",
    description:
      "型紙を彫り、防染糊を置いてから顔料を指で摺り込む型染め。一色ごとに天日で乾かしてから次の色を挿すため、七色使うと七回乾かす。型紙は自分で彫り、同じ図案は二度と彫らない。",
    hp_url: null,
    region: "沖縄県",
    address: "沖縄県那覇市",
    history: "琉球王国時代に王族・士族の衣装として発展した。",
    tags: "染物,布,型染め",
    lang: "ja",
  },
  {
    id: "d018",
    artisan_id: "artisan-demo",
    name: "会津型染め",
    name_kana: "あいづかたぞめ",
    artisan_name: "（架空）猪苗代 悦子",
    description:
      "型紙を彫るのに十日、糊を置いて染めるのに五日かかる型染め。糊は餅粉と糠を練って自分で作る。乾く前に触ると柄が崩れるため、一枚仕上げるまで一切触らない。",
    hp_url: null,
    region: "福島県",
    address: "福島県会津若松市",
    history: "会津は藍染の産地として江戸期から知られる。",
    tags: "染物,布",
    lang: "ja",
  },
  {
    id: "d019",
    artisan_id: "artisan-demo",
    name: "阿波藍染",
    name_kana: "あわあいぞめ",
    artisan_name: "（架空）三木 保",
    description:
      "すくもを発酵させた藍甕に、糸や布を二十回以上浸けては空気に触れさせて発色させる。甕は毎日かき混ぜて温度と発酵具合を確かめる。浸ける回数で色の濃さが変わる。",
    hp_url: null,
    region: "徳島県",
    address: "徳島県徳島市",
    history: "阿波藍は江戸期に全国の藍の大半を占めた。",
    tags: "染物,布,藍",
    lang: "ja",
  },
  {
    id: "d020",
    artisan_id: "artisan-demo",
    name: "出雲藍染",
    name_kana: "いずもあいぞめ",
    artisan_name: "（架空）錦織 保",
    description:
      "地元産の蓼藍から作ったすくもだけを使う藍染め。化学建てはせず、灰汁と発酵の力だけで染液を建てる。建てるのに二週間、安定させるのにさらに一週間かかる。",
    hp_url: null,
    region: "島根県",
    address: "島根県松江市",
    history: "出雲地方では明治期まで藍作が盛んだった。",
    tags: "染物,布,藍",
    lang: "ja",
  },

  // --- 和紙 +4 ---
  {
    id: "d021",
    artisan_id: "artisan-demo",
    name: "因州和紙",
    name_kana: "いんしゅうわし",
    artisan_name: "（架空）山根 修一",
    description:
      "楮の皮を煮て叩き、簀桁を前後に振って漉く流し漉き。一枚を漉くのに数十秒だが、乾燥まで含めると二日かかる。厚みを均一にするため、桁を振る回数を数えながら漉く。",
    hp_url: null,
    region: "鳥取県",
    address: "鳥取県鳥取市",
    history: "因州和紙は書道用紙の産地として知られる。",
    tags: "和紙,文具",
    lang: "ja",
  },
  {
    id: "d022",
    artisan_id: "artisan-demo",
    name: "土佐和紙",
    name_kana: "とさわし",
    artisan_name: "（架空）川村 悠",
    description:
      "楮・三椏・雁皮の三種を漉き分ける。雁皮は繊維が短く扱いにくいため、一人前になるまで五年はかかるとされる。漉いた紙は板に貼って天日で乾かす。",
    hp_url: null,
    region: "高知県",
    address: "高知県いの町",
    history: "土佐和紙は千年以上前から漉かれてきたとされる。",
    tags: "和紙,紙漉き,文具",
    lang: "ja",
  },
  {
    id: "d023",
    artisan_id: "artisan-demo",
    name: "石州和紙",
    name_kana: "せきしゅうわし",
    artisan_name: "（架空）佐々木 昭二",
    description:
      "楮の繊維を三日かけて煮て精製し、トロロアオイの粘りを加えて漉く。強度を出すため繊維を短く切らずに漉くのが特徴で、破れにくい紙になる。",
    hp_url: null,
    region: "島根県",
    address: "島根県浜田市",
    history: "石州和紙は障子紙の産地として発展した。",
    tags: "和紙,紙漉き",
    lang: "ja",
  },
  {
    id: "d024",
    artisan_id: "artisan-demo",
    name: "八女和紙",
    name_kana: "やめわし",
    artisan_name: "（架空）松尾 光一",
    description:
      "地元の提灯や傘に使う和紙を、楮を原料に手漉きする。一日に漉けるのは百数十枚ほどで、天候によって乾燥時間が半日から一日変わる。",
    hp_url: null,
    region: "福岡県",
    address: "福岡県八女市",
    history: "八女は提灯の産地として和紙の需要が生まれた。",
    tags: "和紙,文具",
    lang: "ja",
  },

  // --- 陶磁器 +3 ---
  {
    id: "d025",
    artisan_id: "artisan-demo",
    name: "有田焼",
    name_kana: "ありたやき",
    artisan_name: "（架空）深川 誠一",
    description:
      "陶石を砕いて練った磁土を轆轤で挽き、九百度前後で素焼きしたあと絵付けをして本焼きする。呉須で下絵を描き、上絵付けをする場合はさらに三度目の焼成を行う。",
    hp_url: null,
    region: "佐賀県",
    address: "佐賀県有田町",
    history: "有田は日本で最初に磁器が焼かれた産地とされる。",
    tags: "陶磁器,陶器,食器",
    lang: "ja",
  },
  {
    id: "d026",
    artisan_id: "artisan-demo",
    name: "萩焼",
    name_kana: "はぎやき",
    artisan_name: "（架空）坂田 芳雄",
    description:
      "土を数種類調合し、低い温度でじっくり焼き締める。貫入と呼ぶ細かいひびに茶渋が入り、使うほど色が変わる「萩の七化け」と呼ばれる特徴がある。",
    hp_url: null,
    region: "山口県",
    address: "山口県萩市",
    history: "萩焼は朝鮮から渡った陶工が始めたとされる。",
    tags: "陶磁器,陶器,茶道具",
    lang: "ja",
  },
  {
    id: "d027",
    artisan_id: "artisan-demo",
    name: "壺屋焼",
    name_kana: "つぼややき",
    artisan_name: "（架空）新垣 勝",
    description:
      "泥釉と呼ぶ黒っぽい釉薬をかけて焼く荒焼と、白化粧を施す上焼の二種を手がける。登り窯での焼成には丸一日かけ、薪の投入を交代で続ける。",
    hp_url: null,
    region: "沖縄県",
    address: "沖縄県那覇市",
    history: "壺屋は琉球王府が窯場を集めて作った町。",
    tags: "陶磁器,陶器,酒器",
    lang: "ja",
  },

  // --- 漆器 +3 ---
  {
    id: "d028",
    artisan_id: "artisan-demo",
    name: "会津塗",
    name_kana: "あいづぬり",
    artisan_name: "（架空）五十嵐 信",
    description:
      "下地から上塗りまで二十以上の工程を経る。一回塗るごとに一日から二日乾かして研ぐため、椀一つを仕上げるのに一ヶ月以上かかる。",
    hp_url: null,
    region: "福島県",
    address: "福島県会津若松市",
    history: "会津塗は蒲生氏郷が漆器産業を奨励したのが始まりとされる。",
    tags: "漆器,食器",
    lang: "ja",
  },
  {
    id: "d029",
    artisan_id: "artisan-demo",
    name: "香川漆器",
    name_kana: "かがわしっき",
    artisan_name: "（架空）三谷 修",
    description:
      "漆を彫って模様を出す蒟醤という技法を用いる。彫った溝に色漆を埋めて研ぎ出すため、模様が完成するまでに漆を塗っては研ぐ工程を十回以上繰り返す。",
    hp_url: null,
    region: "香川県",
    address: "香川県高松市",
    history: "蒟醤は江戸後期に東南アジアの技法をもとに確立された。",
    tags: "漆器,食器",
    lang: "ja",
  },
  {
    id: "d030",
    artisan_id: "artisan-demo",
    name: "琉球漆器",
    name_kana: "りゅうきゅうしっき",
    artisan_name: "（架空）玉城 憲一",
    description:
      "堆錦という沖縄独自の技法で、練った色漆を薄く延ばして文様を貼り付ける。デイゴやガジュマルなど南方の木を素地に使うことがある。",
    hp_url: null,
    region: "沖縄県",
    address: "沖縄県那覇市",
    history: "琉球漆器は交易品として東南アジアの技法を取り入れた。",
    tags: "漆器,食器",
    lang: "ja",
  },

  // --- 竹工 +3 ---
  {
    id: "d031",
    artisan_id: "artisan-demo",
    name: "別府竹細工",
    name_kana: "べっぷたけざいく",
    artisan_name: "（架空）首藤 良介",
    description:
      "真竹を幅一ミリ程度のひごに割き、編んで籠を作る。編み方は二百種以上あるとされ、一つの籠に複数の編み方を組み合わせることが多い。",
    hp_url: null,
    region: "大分県",
    address: "大分県別府市",
    history: "別府は温泉客の湯かご需要から竹細工が発展した。",
    tags: "竹工,竹,かご",
    lang: "ja",
  },
  {
    id: "d032",
    artisan_id: "artisan-demo",
    name: "勝山竹細工",
    name_kana: "かつやまたけざいく",
    artisan_name: "（架空）加藤 誠治",
    description:
      "地元の真竹を油抜きしてから編む。花器や行灯を手がけ、ひごの幅を〇.五ミリ単位で揃えることで編み目を均一にしている。",
    hp_url: null,
    region: "岡山県",
    address: "岡山県真庭市",
    history: "勝山は良質な真竹の産地として知られる。",
    tags: "竹工,竹,花器",
    lang: "ja",
  },
  {
    id: "d033",
    artisan_id: "artisan-demo",
    name: "土佐虎斑竹細工",
    name_kana: "とさとらふだけざいく",
    artisan_name: "（架空）田内 修平",
    description:
      "虎の模様に似た斑点が出る虎斑竹だけを使う。斑点は自然にできるもので、良い斑の竹が育つ竹林はごく限られている。杖や花器に加工する。",
    hp_url: null,
    region: "高知県",
    address: "高知県安芸市",
    history: "虎斑竹は安芸市の特定の竹林でしか育たないとされる。",
    tags: "竹工,竹,杖",
    lang: "ja",
  },

  // --- 織物 +3 ---
  {
    id: "d034",
    artisan_id: "artisan-demo",
    name: "久留米絣",
    name_kana: "くるめがすり",
    artisan_name: "（架空）石橋 民江",
    description:
      "糸を先に染め分けてから織る絣織。柄を合わせるため、経糸と緯糸のくくり位置を〇.一ミリ単位で調整する。織り上げるまでに三十以上の工程を要する。",
    hp_url: null,
    region: "福岡県",
    address: "福岡県久留米市",
    history: "久留米絣は江戸後期に一人の少女が考案したと伝わる。",
    tags: "織物,布",
    lang: "ja",
  },
  {
    id: "d035",
    artisan_id: "artisan-demo",
    name: "弓浜絣",
    name_kana: "ゆみはまがすり",
    artisan_name: "（架空）門脇 智子",
    description:
      "木綿の糸を藍で染め、絵絣と呼ぶ具象的な柄を織り出す。柄がずれないよう、糸をくくる作業だけで数日かかる。織り手は現在数人にまで減っている。",
    hp_url: null,
    region: "鳥取県",
    address: "鳥取県境港市",
    history: "弓浜絣は江戸後期に山陰地方で広まった。",
    tags: "織物,布",
    lang: "ja",
  },
  {
    id: "d036",
    artisan_id: "artisan-demo",
    name: "伊予絣",
    name_kana: "いよがすり",
    artisan_name: "（架空）越智 保",
    description:
      "藍で染めた糸を織って幾何学模様を出す。柄合わせのため、織る前にくくった糸の位置を何度も確認する。かつて日本三大絣の一つに数えられた。",
    hp_url: null,
    region: "愛媛県",
    address: "愛媛県松山市",
    history: "伊予絣は明治期に生産量日本一を記録した。",
    tags: "織物,布",
    lang: "ja",
  },

  // --- 金工 +2 ---
  {
    id: "d037",
    artisan_id: "artisan-demo",
    name: "山形鋳物",
    name_kana: "やまがたいもの",
    artisan_name: "（架空）遠藤 一夫",
    description:
      "鋳型に溶かした鉄を流し込み、冷めたら型を割って取り出す。茶道具は肌が薄いのが特徴で、厚みを均一にするため型の隙間を〇.五ミリ単位で調整する。",
    hp_url: null,
    region: "山形県",
    address: "山形県山形市",
    history: "山形鋳物は平安期に鋳物師が移り住んだのが始まりとされる。",
    tags: "金工,鉄,茶道具",
    lang: "ja",
  },
  {
    id: "d038",
    artisan_id: "artisan-demo",
    name: "肥後象がん",
    name_kana: "ひごぞうがん",
    artisan_name: "（架空）松野 一馬",
    description:
      "鉄地に金や銀の細い線を打ち込んで模様を作る。地金に細かい溝を鏨で彫り、そこに金線を埋め込んで叩き締める。溝彫りだけで数日かかる。",
    hp_url: null,
    region: "熊本県",
    address: "熊本県熊本市",
    history: "肥後象がんは刀や鐔の装飾として発展した。",
    tags: "金工,銅,小物",
    lang: "ja",
  },

  // --- ガラス +2 ---
  {
    id: "d039",
    artisan_id: "artisan-demo",
    name: "津軽びいどろ",
    name_kana: "つがるびいどろ",
    artisan_name: "（架空）工藤 学",
    description:
      "千三百度で溶かしたガラスを竿に巻き取り、息を吹き込んで成形する宙吹き。色ガラスを重ねて模様を出す七宝技法も用いる。一点仕上げるのに数分だが、冷ますのに一晩かける。",
    hp_url: null,
    region: "青森県",
    address: "青森県鰺ヶ沢町",
    history: "元は漁業用の浮き玉ガラスを作っていた技術を転用した。",
    tags: "ガラス,器,食器",
    lang: "ja",
  },
  {
    id: "d040",
    artisan_id: "artisan-demo",
    name: "肥前びーどろ",
    name_kana: "ひぜんびーどろ",
    artisan_name: "（架空）副島 誠",
    description:
      "宙吹きでガラスを成形し、道具を使わず息と重力だけで形を整える。竿を回す速さと息の量で厚みを調整するため、感覚がつかめるまで数年かかる。",
    hp_url: null,
    region: "佐賀県",
    address: "佐賀県佐賀市",
    history: "肥前びーどろは幕末に精錬方で作られたのが始まり。",
    tags: "ガラス,器,酒器",
    lang: "ja",
  },

  // --- 楽器 +2 ---
  {
    id: "d041",
    artisan_id: "artisan-demo",
    name: "琉球三線",
    name_kana: "りゅうきゅうさんしん",
    artisan_name: "（架空）平良 信一",
    description:
      "蛇皮を胴に張り、黒檀の棹を組む。皮張りは湿度で張り具合が変わるため天候を見て行う。棹の仕込みには数年寝かせた木材を使う。",
    hp_url: null,
    region: "沖縄県",
    address: "沖縄県沖縄市",
    history: "琉球王国時代に中国から伝わった三弦が起源とされる。",
    tags: "楽器,音が鳴る",
    lang: "ja",
  },
  {
    id: "d042",
    artisan_id: "artisan-demo",
    name: "薩摩琵琶",
    name_kana: "さつまびわ",
    artisan_name: "（架空）東郷 武志",
    description:
      "桑の木をくり抜いて胴を作り、絹糸の弦を張る。胴の厚みを削り出す作業だけで数週間かかり、木材は数年乾燥させたものを使う。",
    hp_url: null,
    region: "鹿児島県",
    address: "鹿児島県鹿児島市",
    history: "薩摩琵琶は武士の士気を鼓舞する目的で広まったとされる。",
    tags: "楽器,音が鳴る",
    lang: "ja",
  },

  // --- 追加補充（金工・ガラス・木工が5件に届いていなかった分） ---
  {
    id: "d043",
    artisan_id: "artisan-demo",
    name: "燕鎚起銅器",
    name_kana: "つばめついきどうき",
    artisan_name: "（架空）玉木 一博",
    description:
      "一枚の銅板を金鎚で叩き絞りながら丸みのある器に仕上げる鎚起という技法。叩く回数は数千回に及び、急須一つで数週間かかる。継ぎ目を作らないため水漏れしない。",
    hp_url: null,
    region: "新潟県",
    address: "新潟県燕市",
    history: "燕は江戸期に和釘作りから銅器へ発展した。",
    tags: "金工,銅,急須",
    lang: "ja",
  },
  {
    id: "d044",
    artisan_id: "artisan-demo",
    name: "薩摩切子",
    name_kana: "さつまきりこ",
    artisan_name: "（架空）川原 誠",
    description:
      "色ガラスを被せたガラスを回転砥石で削り、文様を刻む。薩摩切子は色の層が江戸切子より厚く、削ると独特のぼかしが出る。一度途絶え、昭和末に復元された。",
    hp_url: null,
    region: "鹿児島県",
    address: "鹿児島県鹿児島市",
    history: "幕末に薩摩藩が藩窯として始めたが、明治維新後に一度途絶えた。",
    tags: "ガラス,酒器,切子",
    lang: "ja",
  },
  {
    id: "d045",
    artisan_id: "artisan-demo",
    name: "大川組子",
    name_kana: "おおかわくみこ",
    artisan_name: "（架空）田中 洋二",
    description:
      "釘や接着剤を使わず、木を細かく組んで幾何学模様を作る建具の技術。一枚の欄間に千本近い部材を使うこともあり、〇.一ミリの誤差でも組めなくなる。",
    hp_url: null,
    region: "福岡県",
    address: "福岡県大川市",
    history: "大川は江戸期から続く家具・建具の産地。",
    tags: "木工,建具,家具",
    lang: "ja",
  },
  {
    id: "d046",
    artisan_id: "artisan-demo",
    name: "遠刈田こけし",
    name_kana: "とおがったこけし",
    artisan_name: "（架空）佐藤 誠一",
    description:
      "ろくろで胴を挽き、頭をはめ込んでから顔を描く。系統ごとに描き方の決まりがあり、遠刈田系は重ね菊の模様が特徴とされる。木は数年乾燥させてから使う。",
    hp_url: null,
    region: "宮城県",
    address: "宮城県蔵王町",
    history: "遠刈田はこけし発祥の地の一つとされる。",
    tags: "木工,人形,玩具",
    lang: "ja",
  },
];

