// ローカル開発用のシードデータ。
//
// 紹介機能が作る cards テーブルと同じ形にしてある。
// 統合後は紹介機能が登録したデータを読むので、このファイルは不要になる。
//
// artisan_name に「（架空）」が付いているものは検証用のダミー。
// 産地と品目は実在するが、工房名・職人名は架空。
// 付いていない4件は施設名・住所・公式サイトを実在確認済み（2026-08時点）。

export const cards = [
  {
    id: "c001",
    artisan_id: "org-demo",
    name: "越前和紙",
    name_kana: "えちぜんわし",
    artisan_name: "越前和紙の里 パピルス館",
    description:
      "予約なしで紙漉き体験ができる施設。所要20〜40分で、漉いた紙はその場で持ち帰れる。隣接する卯立の工芸館では、原料づくりから天日干しまでの全工程を見学できる。",
    hp_url: "https://www.echizenwashi.jp/",
    region: "福井県",
    address: "福井県越前市新在家町8-44",
    history: "越前和紙は1500年の歴史を持つとされる産地。",
    tags: "和紙,紙漉き,体験できる,文具",
    lang: "ja",
  },
  {
    id: "c002",
    artisan_id: "org-demo",
    name: "輪島塗",
    name_kana: "わじまぬり",
    artisan_name: "輪島塗会館（輪島漆器商工業協同組合）",
    description:
      "1階に約60軒の漆器店が出店する共同ショップ、2階に製作工程と歴史の資料展示室がある。輪島塗は百以上の工程を分業でこなす。",
    hp_url: "https://wajimanuri.or.jp/",
    region: "石川県",
    address: "石川県輪島市河井町24-55",
    history: "輪島漆器商工業協同組合が運営。",
    tags: "漆器,食器,見学できる,沈金",
    lang: "ja",
  },
  {
    id: "c003",
    artisan_id: "org-demo",
    name: "西陣織",
    name_kana: "にしじんおり",
    artisan_name: "西陣織会館（西陣織工業組合）",
    description:
      "職人による手織の実演、蚕の飼育や座繰りの見学ができる。手織体験では20×30cm程度のテーブルセンターを織れる。西陣織は工程ごとに職人が分かれる分業制。",
    hp_url: "https://nishijin.or.jp/",
    region: "京都府",
    address: "京都府京都市上京区西堀川通元誓願寺上ル竪門前町414",
    history: "西陣織工業組合が運営。",
    tags: "織物,絹,帯,体験できる,実演",
    lang: "ja",
  },
  {
    id: "c004",
    artisan_id: "org-demo",
    name: "南部鉄器",
    name_kana: "なんぶてっき",
    artisan_name: "岩鋳鉄器館",
    description:
      "南部鉄器の製造工程を無料で見学できる工場併設の資料館。鋳型に文様を一粒ずつ押していくあられ模様の工程が見られる。使うほど内側に膜ができて湯の味が変わる。",
    hp_url: "https://iwachu.co.jp/",
    region: "岩手県",
    address: "岩手県盛岡市南仙北2-23-9",
    history: "南部鉄器は江戸期の藩の保護から発展した。",
    tags: "金工,鉄,茶道具,見学できる,急須",
    lang: "ja",
  },
  {
    id: "d001",
    artisan_id: "artisan-demo",
    name: "小鹿田焼 飛び鉋の小鉢",
    name_kana: "おんたやき とびかんなのこばち",
    artisan_name: "（架空）坂本 陽一",
    description:
      "鉋を当てて規則的な刻みを入れる飛び鉋の小鉢。土は地元の山から掘り、唐臼で搗いて作る。素朴で厚みがある。",
    hp_url: null,
    region: "大分県",
    address: "大分県日田市源栄町皿山",
    history: "小鹿田焼は江戸中期から続く。一子相伝で作り手を増やさない方針を守っている。",
    tags: "陶磁器,陶器,器,食器",
    lang: "ja",
  },
  {
    id: "d002",
    artisan_id: "artisan-demo",
    name: "津軽塗 七々子塗の箸",
    name_kana: "つがるぬり ななこぬりのはし",
    artisan_name: "（架空）工藤 佳子",
    description:
      "菜の花の種を蒔いて模様を作る七々子塗。研ぎ出すと小さな輪が浮かぶ。四十以上の工程を経て仕上がる。",
    hp_url: null,
    region: "青森県",
    address: "青森県弘前市",
    history: "藩政時代に始まった塗り。",
    tags: "漆器,食器,箸",
    lang: "ja",
  },
  {
    id: "d003",
    artisan_id: "artisan-demo",
    name: "琉球ガラス 泡入りのグラス",
    name_kana: "りゅうきゅうがらす あわいりのぐらす",
    artisan_name: "（架空）比嘉 直人",
    description:
      "廃瓶を溶かして再生した青いガラス。あえて気泡を残しており、光を通すと水中のように見える。厚手で手に重い。",
    hp_url: null,
    region: "沖縄県",
    address: "沖縄県糸満市",
    history: "戦後の物資不足で米軍の廃瓶を使ったのが始まり。",
    tags: "ガラス,器,食器,夏",
    lang: "ja",
  },
  {
    id: "d004",
    artisan_id: "artisan-demo",
    name: "三味線 紅木の棹",
    name_kana: "しゃみせん こうきのさお",
    artisan_name: "（架空）遠藤 常吉",
    description:
      "インド産の紅木を十年以上寝かせてから削り出す棹。継ぎ目が指に触れないよう精度を合わせる。木の詰まり具合で音が変わる。",
    hp_url: null,
    region: "東京都",
    address: "東京都台東区",
    history: "棹だけを専門に手がけ、組み立ては別の職人に渡す分業。",
    tags: "楽器,木工,三味線,音が鳴る",
    lang: "ja",
  },
  {
    id: "d005",
    artisan_id: "artisan-demo",
    name: "尺八 地無し管",
    name_kana: "しゃくはち じなしかん",
    artisan_name: "（架空）中村 玄樹",
    description:
      "内側に漆を塗り重ねない地無しの竹管。竹そのものの内径で鳴らすため個体差が大きく、息の入れ方で音色が変わる。",
    hp_url: null,
    region: "京都府",
    address: "京都府京都市",
    history: "江戸期の虚無僧尺八の作り方を復元。",
    tags: "楽器,竹,尺八,音が鳴る",
    lang: "ja",
  },
  {
    id: "d006",
    artisan_id: "artisan-demo",
    name: "和太鼓 欅のくり抜き胴",
    name_kana: "わだいこ けやきのくりぬきどう",
    artisan_name: "（架空）浅野 武",
    description:
      "一本の欅を丸ごとくり抜いた胴。乾燥に数年かけ、割れが出ないのを確かめてから皮を張る。低く長く響く。",
    hp_url: null,
    region: "石川県",
    address: "石川県白山市",
    history: "原木の確保が年々難しくなっている。",
    tags: "楽器,木工,太鼓,音が鳴る",
    lang: "ja",
  },
  {
    id: "d007",
    artisan_id: "artisan-demo",
    name: "駿河竹千筋細工 虫籠",
    name_kana: "するがたけせんすじざいく むしかご",
    artisan_name: "（架空）杉山 隆一",
    description:
      "丸く削った竹ひごを差し込んで組む籠。接着剤を使わず竹の弾力だけで留める。透けるほど細い。",
    hp_url: null,
    region: "静岡県",
    address: "静岡県静岡市",
    history: "江戸後期に武士の内職から広まった。作り手は現在十数人。",
    tags: "竹工,小物,竹,夏",
    lang: "ja",
  },
  {
    id: "d008",
    artisan_id: "artisan-demo",
    name: "備前焼 緋襷の徳利",
    name_kana: "びぜんやき ひだすきのとっくり",
    artisan_name: "（架空）森本 一馬",
    description:
      "釉薬を使わず、藁を巻いて焼くと赤い線が走る。窯の中の置き場所で色が決まるため、同じものは二つとない。",
    hp_url: null,
    region: "岡山県",
    address: "岡山県備前市伊部",
    history: "備前は釉薬を使わない焼き締めを千年続けている。",
    tags: "陶磁器,陶器,酒器,器",
    lang: "ja",
  },
  {
    id: "d009",
    artisan_id: "artisan-demo",
    name: "京友禅 手描きの風呂敷",
    name_kana: "きょうゆうぜん てがきのふろしき",
    artisan_name: "（架空）岡村 貴子",
    description:
      "糊で輪郭を置き、筆で一色ずつ挿していく手描き友禅。色の境が滲まない。淡い色を何度も重ねて深さを出す。",
    hp_url: null,
    region: "京都府",
    address: "京都府京都市",
    history: "下絵・糊置き・彩色が別の職人に分かれる分業制。",
    tags: "染物,布,友禅",
    lang: "ja",
  },
  {
    id: "d010",
    artisan_id: "artisan-demo",
    name: "大館曲げわっぱ 弁当箱",
    name_kana: "おおだてまげわっぱ べんとうばこ",
    artisan_name: "（架空）佐藤 建二",
    description:
      "秋田杉を煮て柔らかくし、曲げて桜の皮で縫い留める。木が余分な水分を吸うので冷めた米がべたつかない。",
    hp_url: null,
    region: "秋田県",
    address: "秋田県大館市",
    history: "藩政期に下級武士の内職として奨励された。",
    tags: "木工,弁当箱,杉,贈り物",
    lang: "ja",
  },
  {
    id: "d011",
    artisan_id: "artisan-demo",
    name: "江戸切子 魚子紋の冷酒杯",
    name_kana: "えどきりこ ななこもんのれいしゅはい",
    artisan_name: "（架空）堀口 誠",
    description:
      "色被せガラスの表面を回転砥石で削り、細かい格子を刻む。透明な部分と色の対比が出る。手に取ると角がざらつく。",
    hp_url: null,
    region: "東京都",
    address: "東京都江東区",
    history: "幕末に江戸で始まったガラス加工。",
    tags: "ガラス,酒器,切子,夏,贈り物",
    lang: "ja",
  },
  {
    id: "d012",
    artisan_id: "artisan-demo",
    name: "高岡銅器 花器",
    name_kana: "たかおかどうき かき",
    artisan_name: "（架空）般若 秀樹",
    description:
      "鋳込んだ銅に薬品をかけて色を出す着色仕上げ。緑青とも黒ともつかない色に変化する。ずっしり重い。",
    hp_url: null,
    region: "富山県",
    address: "富山県高岡市",
    history: "加賀藩が鋳物師を招いたのが始まり。着色は専門の職人が担う。",
    tags: "金工,銅,花器",
    lang: "ja",
  },
  {
    id: "d013",
    artisan_id: "artisan-demo",
    name: "本場大島紬 泥染めの反物",
    name_kana: "ほんばおおしまつむぎ どろぞめのたんもの",
    artisan_name: "（架空）肥後 明美",
    description:
      "テーチ木で染めた糸を泥田に浸して黒く発色させる。泥に含まれる鉄分と反応する。軽くて皺になりにくい。",
    hp_url: null,
    region: "鹿児島県",
    address: "鹿児島県奄美市",
    history: "締機・泥染め・織りがそれぞれ別の職人に分かれる。",
    tags: "織物,絹,紬",
    lang: "ja",
  },
  {
    id: "d014",
    artisan_id: "artisan-demo",
    name: "播州そろばん 樺の玉",
    name_kana: "ばんしゅうそろばん かばのたま",
    artisan_name: "（架空）宮永 敏夫",
    description:
      "樺の玉を一粒ずつ削り、竹の軸に通す。指で弾いたときの音と止まり方が揃うよう玉の重さを合わせる。",
    hp_url: null,
    region: "兵庫県",
    address: "兵庫県小野市",
    history: "玉・軸・枠が別々の職人による分業。",
    tags: "木工,文具,そろばん,音が鳴る",
    lang: "ja",
  },
  {
    id: "d015",
    artisan_id: "artisan-demo",
    name: "岩谷堂箪笥 鉄製手掛かり",
    name_kana: "いわやどうたんす てつせいてがかり",
    artisan_name: "（架空）及川 正",
    description:
      "欅の箪笥に打つ手打ちの鉄金具。唐草を透かし彫りにする。木地師と金具師が別々に作り、最後に合わせる。",
    hp_url: null,
    region: "岩手県",
    address: "岩手県奥州市",
    history: "金具を打てる職人が減っている。",
    tags: "木工,家具,金具",
    lang: "ja",
  },
  {
    id: "d016",
    artisan_id: "artisan-demo",
    name: "丸亀うちわ 平柄",
    name_kana: "まるがめうちわ ひらえ",
    artisan_name: "（架空）香川 実",
    description:
      "一本の竹を割いて骨と柄を一体で作る平柄。骨が細かいほど風が柔らかい。和紙を貼って縁を留める。",
    hp_url: null,
    region: "香川県",
    address: "香川県丸亀市",
    history: "金比羅参りの土産として江戸期に広まった。",
    tags: "竹工,うちわ,夏,贈り物",
    lang: "ja",
  },
];

